sudo: required

language: java

jdk: oraclejdk11

services:
  - docker

install:
  - ./mvnw clean install

script:
  - echo "no scripts"

after_success:
  - docker --version
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_REPO
  - docker build -t noves-bike-api .
  - docker tag noves-bike-api:latest $AWS_REPO_URL
  - docker push $AWS_REPO_URL

cache:
  directories:
    - $HOME/.m2
