version: "3"

services:
  noves-api:
    build: .
    image: noves-bike-api
    container_name: noves-api
    environment:
      PROFILE: ${PROFILE}

      JWT_SECRET: ${JWT_SECRET}

      DB_HOST: db-noves
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_PORT: ${EMAIL_PORT}

      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_BUCKET: ${AWS_BUCKET}
      AWS_URL_EXPIRATION: ${AWS_URL_EXPIRATION}

    depends_on:
      - db-noves
    networks:
      - noves-bike
    ports:
      - "8080:8080"

  db-noves:
    image: postgres:9.6.23-alpine
    container_name: db-noves
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    networks:
      - noves-bike
    volumes:
      - noves-bike:/var/lib/postgresql/data

volumes:
  noves-bike:

networks:
  noves-bike:
    driver: bridge