spring:
  mail:
    host: ${EMAIL_HOST}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    driverClassName: org.h2.Driver
    password: ''
    username: sa
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
