spring:
  # run application mode
  profiles:
    active: ${PROFILE:test}

  jpa:
    open-in-view: false

  # enable snack_case for response JSON
  jackson:
    property-naming-strategy: SNAKE_CASE

  # file size limit
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 6MB

  # e-mail configuration
  mail:
    host: ${EMAIL_HOST}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    port: ${EMAIL_PORT}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_SECRET:testprofile}
  expiration: 1800000

#logging:
#  level:
#    root: DEBUG

storage:
  aws:
    s3:
      access:
        key:
          id: ${AWS_ACCESS_KEY_ID}
      secret:
        access:
          key: ${AWS_SECRET_ACCESS_KEY}
      default:
        region: ${AWS_DEFAULT_REGION}
      bucket: ${AWS_BUCKET}
      url:
        expiration: ${AWS_URL_EXPIRATION:5}


