spring:
  mail:
    properties:
      mail:
        smtp:
          ssl:
            enable: false

  datasource:
    url: jdbc:postgresql://db-noves:5432/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create

#logging:
#  level:
#    root: DEBUG
