spring:
  profiles:
    active: ${PROFILE:test}
  jpa:
    open-in-view: false
  jackson:
    property-naming-strategy: SNAKE_CASE

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_SECRET:testprofile}
  expiration: 1800000


